/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.views.municipality;

import app.controllers.MunicipalityController;
import app.entities.Municipality;
import helpers.Dialog;
import helpers.Log;
import java.awt.Color;
import javax.swing.JDesktopPane;

/**
 *
 * @author raulsm
 */
public class MunicipalityEditJInternalFrame extends javax.swing.JInternalFrame {

    private final JDesktopPane jDesktopPanelContainer;
    
    /**
     * Creates new form MunicipalityJInternalFrame
     */
    public MunicipalityEditJInternalFrame(JDesktopPane jDesktopPanelContainer) {
        initComponents();
        this.jDesktopPanelContainer = jDesktopPanelContainer;
        jTextFieldMunicipioId.setVisible(false);
    }

    /**
     * Load Data.
     * @param municipality
     */
    public void loadData(Municipality municipality) {        
        jTextFieldMunicipioName.setText(municipality.getName());
        jComboBoxMunicipioCategory.setSelectedIndex(0); // @TODO
        jTextFieldMunicipioId.setText(String.valueOf(municipality.getId()));
        jButtonMunicipioUpdate.setEnabled(validateInputs());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMunicipioName = new javax.swing.JLabel();
        jTextFieldMunicipioName = new javax.swing.JTextField();
        jLabelMunicipioCategoria = new javax.swing.JLabel();
        jButtonMunicipioUpdate = new javax.swing.JButton();
        jComboBoxMunicipioCategory = new javax.swing.JComboBox<>();
        jTextFieldMunicipioId = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Municipio");
        setToolTipText("");

        jLabelMunicipioName.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelMunicipioName.setText("Nombre del municipio:");

        jTextFieldMunicipioName.setToolTipText("Introducir nombre del municipio");

        jLabelMunicipioCategoria.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelMunicipioCategoria.setText("Categoría del municipio:");

        jButtonMunicipioUpdate.setText("Actualizar");
        jButtonMunicipioUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMunicipioUpdateActionPerformed(evt);
            }
        });

        jComboBoxMunicipioCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));

        jTextFieldMunicipioId.setEditable(false);
        jTextFieldMunicipioId.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMunicipioName)
                    .addComponent(jLabelMunicipioName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMunicipioUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxMunicipioCategory, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMunicipioCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldMunicipioId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMunicipioName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMunicipioName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMunicipioCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxMunicipioCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMunicipioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jButtonMunicipioUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMunicipioUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMunicipioUpdateActionPerformed
        try {

            int id = Integer.parseInt(jTextFieldMunicipioId.getText());
            Municipality municipality = MunicipalityController.findById(id);

            municipality.setName(getInputName());
            municipality.setCategoryId(Integer.parseInt(getInputCategory()));

            MunicipalityController.update(id, municipality);
            
            Dialog.info("Municipio actualizado correctamente", "Info");
        } catch (NumberFormatException e) {
            Log.error(e);
            Dialog.error(e.getMessage(), "Error actualizando municipio");
        }
    }//GEN-LAST:event_jButtonMunicipioUpdateActionPerformed

    /**
     * Validate Inputs.
     *
     * @return True if inputs are valid
     */
    private Boolean validateInputs() {
        return validateInputName() && validateInputCategory();
    }

    /**
     * Validate Input Name.
     *
     * @return
     */
    private Boolean validateInputName() {
        String name = getInputName();
        Boolean isValid = name.length() > 0 && name.length() <= 30;

        if (isValid || name.length() == 0) {
            jTextFieldMunicipioName.setBackground(Color.white);
        } else {
            jTextFieldMunicipioName.setBackground(Color.orange);
        }

        return isValid;
    }

    /**
     * Validate Input Category.
     *
     * @return
     */
    private Boolean validateInputCategory() {
        // TODO: Validation
        //String category = getInputCategory();
        
        Boolean isValid = true;

        if (isValid) {
            jComboBoxMunicipioCategory.setBackground(Color.white);
        } else {
            jComboBoxMunicipioCategory.setBackground(Color.orange);
        }

        return isValid;
    }

    /**
     * Get Input Name.
     *
     * @return Input Name
     */
    private String getInputName() {
        return jTextFieldMunicipioName.getText();
    }

    /**
     * Get Input Category.
     *
     * @return Input Category.
     */
    private String getInputCategory() {
        return jComboBoxMunicipioCategory.getSelectedItem().toString();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMunicipioUpdate;
    private javax.swing.JComboBox<String> jComboBoxMunicipioCategory;
    private javax.swing.JLabel jLabelMunicipioCategoria;
    private javax.swing.JLabel jLabelMunicipioName;
    private javax.swing.JTextField jTextFieldMunicipioId;
    private javax.swing.JTextField jTextFieldMunicipioName;
    // End of variables declaration//GEN-END:variables
}
