/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.views.municipality;

import app.controllers.MunicipalityController;
import app.entities.Municipality;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raulsm
 */
public class MunicipalityListJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form MunicipalityJInternalFrame
     */
    public MunicipalityListJInternalFrame() {
        initComponents();
        loadData();
    }

    /**
     * Load Data.
     */
    public void loadData() {
        DefaultTableModel model = (DefaultTableModel) jTableMunicipies.getModel();
        
        // @TODO: Load Data
        List<Municipality> items = MunicipalityController.list();
        
        // @TODO: Add data
        Object rowData[] = new Object[items.size()];
        for (int i = 0; i < items.size(); i++) {
            rowData[0] = items.get(i).getId();
            rowData[1] = items.get(i).getName();
            rowData[2] = items.get(i).getCategoryId();
            
            model.addRow(rowData);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMunicipies = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listado Municipios");
        setToolTipText("");

        jTableMunicipies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMunicipies.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableMunicipies);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMunicipies;
    // End of variables declaration//GEN-END:variables
}
