/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.views.convocatory;

import app.controllers.ConvocatoryController;
import app.entities.Convocatory;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raulsm
 */
public class ConvocatoryListJInternalFrame extends javax.swing.JInternalFrame {

    private final JDesktopPane jDesktopPanelContainer;
    
    /**
     * Creates new form MunicipalityJInternalFrame
     * @param jDesktopPanelContaine
     */
    public ConvocatoryListJInternalFrame(JDesktopPane jDesktopPanelContaine) {
        initComponents();
        this.jDesktopPanelContainer = jDesktopPanelContaine;
        loadData();
    }

    /**
     * Load Data.
     */
    public void loadData() {
        DefaultTableModel model = (DefaultTableModel) jTableConvocatories.getModel();
        
        // @TODO: Load Data
        List<Convocatory> items = ConvocatoryController.list();
        
        // @TODO: Add data
        Object rowData[] = new Object[model.getColumnCount()];
                
        for (int i = 0; i < items.size(); i++) {
            rowData[0] = items.get(i).getId();
            rowData[1] = items.get(i).getName();
            rowData[2] = items.get(i).getStartDate().toString();
            rowData[3] = items.get(i).getEndDate().toString();
            rowData[4] = items.get(i).getIsValid();
            
            model.addRow(rowData);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConvocatories = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listado Municipios");
        setToolTipText("");

        jTableConvocatories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "start_date", "end_date", "is_valid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConvocatories.getTableHeader().setReorderingAllowed(false);
        jTableConvocatories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConvocatoriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConvocatories);

        jLabel1.setText("Seleccionar un registro para visualizar su información y poder editar y eliminar.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableConvocatoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConvocatoriesMouseClicked
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int id = Integer.parseInt(source.getModel().getValueAt(row, 0).toString());
        
        Convocatory convocatory = ConvocatoryController.findById(id);

        ConvocatoryShowJInternalFrame convocatoryShow = new ConvocatoryShowJInternalFrame(jDesktopPanelContainer);
        jDesktopPanelContainer.add(convocatoryShow);
        convocatoryShow.loadData(convocatory);
        
        this.hide();
        
        convocatoryShow.setVisible(true);
    }//GEN-LAST:event_jTableConvocatoriesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConvocatories;
    // End of variables declaration//GEN-END:variables
}
