/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.views.convocatory;

import app.controllers.ConvocatoryController;
import app.entities.Convocatory;
import helpers.Dialog;
import helpers.Log;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author raulsm
 */
public class ConvocatoryEditJInternalFrame extends javax.swing.JInternalFrame {

    private final JDesktopPane jDesktopPanelContainer;
    
    /**
     * Creates new form ConvocatoryShowJInternalFrame
     * @param jDesktopPanelContainer
     */
    public ConvocatoryEditJInternalFrame(JDesktopPane jDesktopPanelContainer) {
        initComponents();
        this.jDesktopPanelContainer = jDesktopPanelContainer;
        jTextFieldConvocatoryId.setVisible(false);
    }

    /**
     * Load Data.
     * @param convocatory
     */
    public void loadData(Convocatory convocatory) {        
        jTextFieldConvocatoryName.setText(convocatory.getName());
        jTextAreaConvocatoryDescription.setText(convocatory.getDescription());
        jDateChooserStartDate.setDateFormatString(convocatory.getStartDate().toString());
        jDateChooserEndDate.setDateFormatString(convocatory.getEndDate().toString());
        jCheckBoxConvocatoryStatus.setSelected(convocatory.getIsValid());
        
        jTextFieldConvocatoryId.setText(String.valueOf(convocatory.getId()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConvocatoryName = new javax.swing.JLabel();
        jTextFieldConvocatoryName = new javax.swing.JTextField();
        jLabelConvocatoryDescription = new javax.swing.JLabel();
        jButtonConvocatoryUpdate = new javax.swing.JButton();
        jTextFieldConvocatoryId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConvocatoryDescription = new javax.swing.JTextArea();
        jLabelConvocatoryEndDate1 = new javax.swing.JLabel();
        jCheckBoxConvocatoryStatus = new javax.swing.JCheckBox();
        jLabelConvocatoryStartDate = new javax.swing.JLabel();
        jDateChooserStartDate = new com.toedter.calendar.JDateChooser();
        jLabelConvocatoryStatus = new javax.swing.JLabel();
        jDateChooserEndDate = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Convocatoria");
        setToolTipText("");

        jLabelConvocatoryName.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelConvocatoryName.setText("Nombre de la convocatoria:");

        jTextFieldConvocatoryName.setToolTipText("Introducir nombre del municipio");
        jTextFieldConvocatoryName.setEnabled(false);

        jLabelConvocatoryDescription.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelConvocatoryDescription.setText("Descripción:");

        jButtonConvocatoryUpdate.setText("Actualizar");
        jButtonConvocatoryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvocatoryUpdateActionPerformed(evt);
            }
        });

        jTextFieldConvocatoryId.setEditable(false);
        jTextFieldConvocatoryId.setEnabled(false);

        jTextAreaConvocatoryDescription.setEditable(false);
        jTextAreaConvocatoryDescription.setColumns(20);
        jTextAreaConvocatoryDescription.setRows(5);
        jTextAreaConvocatoryDescription.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaConvocatoryDescription);

        jLabelConvocatoryEndDate1.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelConvocatoryEndDate1.setText("Fecha inicio:");

        jCheckBoxConvocatoryStatus.setText("¿Activa?");

        jLabelConvocatoryStartDate.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelConvocatoryStartDate.setText("Fecha inicio:");

        jDateChooserStartDate.setDateFormatString("yyyy-MM-dd");

        jLabelConvocatoryStatus.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelConvocatoryStatus.setText("Estado Apertura?:");

        jDateChooserEndDate.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonConvocatoryUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldConvocatoryName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelConvocatoryName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelConvocatoryDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTextFieldConvocatoryId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelConvocatoryStartDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserStartDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConvocatoryEndDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxConvocatoryStatus)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabelConvocatoryStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConvocatoryName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldConvocatoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelConvocatoryDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConvocatoryStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConvocatoryEndDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConvocatoryStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxConvocatoryStatus)
                    .addComponent(jDateChooserEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldConvocatoryId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConvocatoryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConvocatoryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvocatoryUpdateActionPerformed
        try {

            int id = Integer.parseInt(jTextFieldConvocatoryId.getText());
//            Convocatory convocatory = MunicipalityController.findById(id);
//            
//            ConvocatoryEditJInternalFrame convocatoryEdit = new ConvocatoryEditJInternalFrame();
//        
//            jDesktopPanelContainer.add(convocatoryEdit);
//        
//            // Load municipio info in view
//            convocatoryEdit.loadData(convocatory);
//            
//            convocatoryEdit.setVisible(true);
        } catch (NumberFormatException e) {
            Log.error(e);
            Dialog.error(e.getMessage(), "Error editar municipio");
        }
    }//GEN-LAST:event_jButtonConvocatoryUpdateActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvocatoryUpdate;
    private javax.swing.JCheckBox jCheckBoxConvocatoryStatus;
    private com.toedter.calendar.JDateChooser jDateChooserEndDate;
    private com.toedter.calendar.JDateChooser jDateChooserStartDate;
    private javax.swing.JLabel jLabelConvocatoryDescription;
    private javax.swing.JLabel jLabelConvocatoryEndDate1;
    private javax.swing.JLabel jLabelConvocatoryName;
    private javax.swing.JLabel jLabelConvocatoryStartDate;
    private javax.swing.JLabel jLabelConvocatoryStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaConvocatoryDescription;
    private javax.swing.JTextField jTextFieldConvocatoryId;
    private javax.swing.JTextField jTextFieldConvocatoryName;
    // End of variables declaration//GEN-END:variables
}
