/**
 * Convocatory Show JInternal Frame.
 *
 * @author raulsm
 * @version 1.0.0
 */
package app.views.convocatory;

import app.Main;
import app.controllers.ConvocatoryController;
import app.entities.Convocatory;
import app.entities.DocumentType;
import app.entities.User;
import helpers.Dialog;
import helpers.Log;
import helpers.Role;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 * Convocatory Show JInternal Frame.
 *
 * @author raulsm
 * @version 1.0.0
 */
public class ConvocatoryShowJInternalFrame extends javax.swing.JInternalFrame {

    private final JDesktopPane jDesktopPanelContainer;

    /**
     * Creates new form ConvocatoryShowJInternalFrame
     *
     * @param jDesktopPanelContainer Desktop Panel Container
     */
    public ConvocatoryShowJInternalFrame(JDesktopPane jDesktopPanelContainer) {
        initComponents();
        this.jDesktopPanelContainer = jDesktopPanelContainer;
        jTextFieldConvocatoryId.setVisible(false);

        // Show or Hide Sections
        User authUser = Main.getAuthUser();
        showHideSections(authUser);
    }

    /**
     * Show or Hide Sections by User
     *
     * @param user Auth User
     */
    private void showHideSections(User user) {
        int roleId = user.getRoleId();

        if (roleId != Role.ADMININISTRATOR && roleId != Role.FISCAL_GENERAL) {
            jButtonConvocatoryDelete.setVisible(false);
            jButtonConvocatoryEdit.setVisible(false);
        }
    }

    /**
     * Load Data.
     *
     * @param convocatory Convocatory.
     */
    public void loadData(Convocatory convocatory) {
        jTextFieldConvocatoryId.setText(String.valueOf(convocatory.getId()));

        jTextFieldConvocatoryName.setText(convocatory.getName());
        jTextAreaConvocatoryDescription.setText(convocatory.getDescription());
        jDateChooserStartDate.setDate(convocatory.getStartDate());
        jDateChooserEndDate.setDate(convocatory.getEndDate());
        jCheckBoxConvocatoryStatus.setSelected(convocatory.getIsValid());

        // Set documents
        List<DocumentType> documentTypes = convocatory.getDocumentsTypes();
        setDocumentsTypes(documentTypes);
    }

    /**
     * Set Documents Types
     *
     * @param documentTypes Documents Types
     */
    private void setDocumentsTypes(List<DocumentType> documentTypes) {
        for (DocumentType documentType : documentTypes) {
            if (documentType.getId() == 1) {
                jCheckBoxDocumentTypeId1.setSelected(true);
            }
            if (documentType.getId() == 2) {
                jCheckBoxDocumentTypeId2.setSelected(true);
            }
            if (documentType.getId() == 3) {
                jCheckBoxDocumentTypeId3.setSelected(true);
            }
            if (documentType.getId() == 4) {
                jCheckBoxDocumentTypeId4.setSelected(true);
            }
            if (documentType.getId() == 5) {
                jCheckBoxDocumentTypeId5.setSelected(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConvocatoryName = new javax.swing.JLabel();
        jTextFieldConvocatoryName = new javax.swing.JTextField();
        jLabelConvocatoryDescription = new javax.swing.JLabel();
        jButtonConvocatoryEdit = new javax.swing.JButton();
        jTextFieldConvocatoryId = new javax.swing.JTextField();
        jButtonConvocatoryDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConvocatoryDescription = new javax.swing.JTextArea();
        jLabelConvocatoryEndDate1 = new javax.swing.JLabel();
        jCheckBoxConvocatoryStatus = new javax.swing.JCheckBox();
        jLabelConvocatoryStartDate = new javax.swing.JLabel();
        jDateChooserStartDate = new com.toedter.calendar.JDateChooser();
        jLabelConvocatoryStatus = new javax.swing.JLabel();
        jDateChooserEndDate = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxDocumentTypeId1 = new javax.swing.JCheckBox();
        jCheckBoxDocumentTypeId2 = new javax.swing.JCheckBox();
        jCheckBoxDocumentTypeId3 = new javax.swing.JCheckBox();
        jCheckBoxDocumentTypeId4 = new javax.swing.JCheckBox();
        jCheckBoxDocumentTypeId5 = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ver Convocatoria");
        setToolTipText("");

        jLabelConvocatoryName.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelConvocatoryName.setText("Nombre de la convocatoria:");

        jTextFieldConvocatoryName.setToolTipText("Introducir nombre del municipio");
        jTextFieldConvocatoryName.setEnabled(false);

        jLabelConvocatoryDescription.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelConvocatoryDescription.setText("Descripción:");

        jButtonConvocatoryEdit.setText("Editar");
        jButtonConvocatoryEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvocatoryEditActionPerformed(evt);
            }
        });

        jTextFieldConvocatoryId.setEditable(false);
        jTextFieldConvocatoryId.setEnabled(false);

        jButtonConvocatoryDelete.setBackground(new java.awt.Color(255, 153, 153));
        jButtonConvocatoryDelete.setText("Eliminar");
        jButtonConvocatoryDelete.setBorderPainted(false);
        jButtonConvocatoryDelete.setOpaque(true);
        jButtonConvocatoryDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvocatoryDeleteActionPerformed(evt);
            }
        });

        jTextAreaConvocatoryDescription.setEditable(false);
        jTextAreaConvocatoryDescription.setColumns(20);
        jTextAreaConvocatoryDescription.setRows(5);
        jTextAreaConvocatoryDescription.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaConvocatoryDescription);

        jLabelConvocatoryEndDate1.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelConvocatoryEndDate1.setText("Fecha inicio:");

        jCheckBoxConvocatoryStatus.setText("¿Activa?");
        jCheckBoxConvocatoryStatus.setEnabled(false);

        jLabelConvocatoryStartDate.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelConvocatoryStartDate.setText("Fecha inicio:");

        jDateChooserStartDate.setDateFormatString("yyyy-MM-dd");
        jDateChooserStartDate.setEnabled(false);

        jLabelConvocatoryStatus.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelConvocatoryStatus.setText("Estado Apertura?:");

        jDateChooserEndDate.setDateFormatString("yyyy-MM-dd");
        jDateChooserEndDate.setEnabled(false);

        jLabel1.setText("Documentos necesarios:");

        jCheckBoxDocumentTypeId1.setText("Libro Diario");
        jCheckBoxDocumentTypeId1.setEnabled(false);

        jCheckBoxDocumentTypeId2.setText("Libro Mayor");
        jCheckBoxDocumentTypeId2.setEnabled(false);

        jCheckBoxDocumentTypeId3.setText("Balance de Sumas y Saldos");
        jCheckBoxDocumentTypeId3.setEnabled(false);

        jCheckBoxDocumentTypeId4.setText("Registro de Ingreso de Caja");
        jCheckBoxDocumentTypeId4.setEnabled(false);

        jCheckBoxDocumentTypeId5.setText("Registro de Movimientos de Bancos");
        jCheckBoxDocumentTypeId5.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldConvocatoryName)
                    .addComponent(jLabelConvocatoryName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelConvocatoryDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonConvocatoryDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConvocatoryEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldConvocatoryId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelConvocatoryStartDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserStartDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConvocatoryEndDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxConvocatoryStatus)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabelConvocatoryStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxDocumentTypeId1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxDocumentTypeId2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxDocumentTypeId3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxDocumentTypeId4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxDocumentTypeId5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConvocatoryName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldConvocatoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelConvocatoryDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConvocatoryStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConvocatoryEndDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConvocatoryStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxConvocatoryStatus)
                    .addComponent(jDateChooserEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDocumentTypeId1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDocumentTypeId2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDocumentTypeId3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDocumentTypeId4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDocumentTypeId5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldConvocatoryId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConvocatoryEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConvocatoryDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unused")
    private void jButtonConvocatoryEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvocatoryEditActionPerformed
        try {

            int id = Integer.parseInt(jTextFieldConvocatoryId.getText());
            Convocatory convocatory = ConvocatoryController.findById(id);

            ConvocatoryEditJInternalFrame convocatoryEdit = new ConvocatoryEditJInternalFrame();

            jDesktopPanelContainer.add(convocatoryEdit);

            // Load convocatory info in view
            convocatoryEdit.loadData(convocatory);

            this.hide();

            convocatoryEdit.setVisible(true);
        } catch (NumberFormatException e) {
            Log.error(e);
            Dialog.error(e.getMessage(), "Error editar convocatoria");
        }
    }//GEN-LAST:event_jButtonConvocatoryEditActionPerformed

    @SuppressWarnings("unused")
    private void jButtonConvocatoryDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvocatoryDeleteActionPerformed
        int input = JOptionPane.showConfirmDialog(null, "Deseas eliminar?");
        // 0=yes, 1=no, 2=cancel

        if (input == 0) {
            // Delete
            int id = Integer.parseInt(jTextFieldConvocatoryId.getText());
            boolean status = ConvocatoryController.delete(id);

            if (status) {
                Dialog.info("Convocatoria eliminado correctamente", "Info");

                this.hide();
            } else {
                Dialog.error("Convocatoria no se ha eliminado", "Error");
            }
        }

    }//GEN-LAST:event_jButtonConvocatoryDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvocatoryDelete;
    private javax.swing.JButton jButtonConvocatoryEdit;
    private javax.swing.JCheckBox jCheckBoxConvocatoryStatus;
    private javax.swing.JCheckBox jCheckBoxDocumentTypeId1;
    private javax.swing.JCheckBox jCheckBoxDocumentTypeId2;
    private javax.swing.JCheckBox jCheckBoxDocumentTypeId3;
    private javax.swing.JCheckBox jCheckBoxDocumentTypeId4;
    private javax.swing.JCheckBox jCheckBoxDocumentTypeId5;
    private com.toedter.calendar.JDateChooser jDateChooserEndDate;
    private com.toedter.calendar.JDateChooser jDateChooserStartDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelConvocatoryDescription;
    private javax.swing.JLabel jLabelConvocatoryEndDate1;
    private javax.swing.JLabel jLabelConvocatoryName;
    private javax.swing.JLabel jLabelConvocatoryStartDate;
    private javax.swing.JLabel jLabelConvocatoryStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaConvocatoryDescription;
    private javax.swing.JTextField jTextFieldConvocatoryId;
    private javax.swing.JTextField jTextFieldConvocatoryName;
    // End of variables declaration//GEN-END:variables
}
