/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.views.users;

import app.controllers.UserController;
import app.dao.UserRoleDao;
import app.entities.User;
import app.entities.UserRole;
import helpers.Dialog;
import helpers.Log;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;

/**
 *
 * @author raulsm
 */
public class UserEditJInternalFrame extends javax.swing.JInternalFrame {

    private final JDesktopPane jDesktopPanelContainer;
    
    /**
     * Creates new form MunicipalityJInternalFrame
     */
    public UserEditJInternalFrame(JDesktopPane jDesktopPanelContainer) {
        initComponents();
        this.jDesktopPanelContainer = jDesktopPanelContainer;
        jTextFieldUserId.setVisible(false);
    }

    /**
     * Load Data.
     * @param user
     */
    public void loadData(User user) {        
//        jTextFieldMunicipioName.setText(user.getName());
//        jComboBoxMunicipioCategory.setSelectedIndex(0); // @TODO
//        jTextFieldMunicipioId.setText(String.valueOf(user.getId()));
//        jButtonMunicipioUpdate.setEnabled(validateInputs());


        // Traer de base de datos el listado de roles y agregar al combobox
        List<UserRole> userRoles = (new UserRoleDao()).all();
        
        DefaultComboBoxModel defaultComboBoxModel = (DefaultComboBoxModel) jComboBoxUserRole.getModel();
        defaultComboBoxModel.removeAllElements();
        
        for(UserRole userRole : userRoles) {
            defaultComboBoxModel.addElement(userRole);
        }
        
        // Set user role    
        defaultComboBoxModel.setSelectedItem(user.getUserRole());
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUserUpdate = new javax.swing.JButton();
        jLabelUserMunicipality = new javax.swing.JLabel();
        jLabelUserRole = new javax.swing.JLabel();
        jPasswordFieldUserPassword = new javax.swing.JPasswordField();
        jLabelUserPassword = new javax.swing.JLabel();
        jTextFieldUserLogin = new javax.swing.JTextField();
        jLabelUserLogin = new javax.swing.JLabel();
        jTextFieldUserId = new javax.swing.JTextField();
        jComboBoxUserRole = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Usuario");
        setToolTipText("");

        jButtonUserUpdate.setText("Actualizar");
        jButtonUserUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserUpdateActionPerformed(evt);
            }
        });

        jLabelUserMunicipality.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelUserMunicipality.setText("Municipio usuario:");

        jLabelUserRole.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelUserRole.setText("Role usuario:");

        jLabelUserPassword.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelUserPassword.setText("Contraseña usuario:");

        jTextFieldUserLogin.setToolTipText("Introducir nombre del municipio");

        jLabelUserLogin.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelUserLogin.setText("Login usuario:");

        jTextFieldUserId.setEditable(false);
        jTextFieldUserId.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUserUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addComponent(jTextFieldUserLogin)
                    .addComponent(jLabelUserLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUserPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldUserPassword)
                    .addComponent(jLabelUserRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUserMunicipality, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBoxUserRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserRole)
                .addGap(5, 5, 5)
                .addComponent(jComboBoxUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserMunicipality, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jTextFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jButtonUserUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUserUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserUpdateActionPerformed
        try {

            int id = Integer.parseInt(jTextFieldUserId.getText());
            User user = UserController.findById(id);

//            user.setName(getInputName());
//            user.setCategoryId(Integer.parseInt(getInputCategory()));
//
//            UserController.update(id, user);
            
            Dialog.info("Usuario actualizado correctamente", "Info");
        } catch (NumberFormatException e) {
            Log.error(e);
            Dialog.error(e.getMessage(), "Error actualizando usuario");
        }
    }//GEN-LAST:event_jButtonUserUpdateActionPerformed

    /**
     * Validate Inputs.
     *
     * @return True if inputs are valid
     */
//    private Boolean validateInputs() {
//        return validateInputName() && validateInputCategory();
//    }

    /**
     * Validate Input Name.
     *
     * @return
     */
//    private Boolean validateInputName() {
//        String name = getInputName();
//        Boolean isValid = name.length() > 0 && name.length() <= 30;
//
//        if (isValid || name.length() == 0) {
//            jTextFieldMunicipioName.setBackground(Color.white);
//        } else {
//            jTextFieldMunicipioName.setBackground(Color.orange);
//        }
//
//        return isValid;
//    }

    /**
     * Validate Input Category.
     *
     * @return
     */
//    private Boolean validateInputCategory() {
//        // TODO: Validation
//        //String category = getInputCategory();
//        
//        Boolean isValid = true;
//
//        if (isValid) {
//            jComboBoxMunicipioCategory.setBackground(Color.white);
//        } else {
//            jComboBoxMunicipioCategory.setBackground(Color.orange);
//        }
//
//        return isValid;
//    }

    /**
     * Get Input Name.
     *
     * @return Input Name
     */
//    private String getInputName() {
//        return jTextFieldMunicipioName.getText();
//    }

    /**
     * Get Input Category.
     *
     * @return Input Category.
     */
//    private String getInputCategory() {
//        return jComboBoxMunicipioCategory.getSelectedItem().toString();
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUserUpdate;
    private javax.swing.JComboBox<String> jComboBoxUserRole;
    private javax.swing.JLabel jLabelUserLogin;
    private javax.swing.JLabel jLabelUserMunicipality;
    private javax.swing.JLabel jLabelUserPassword;
    private javax.swing.JLabel jLabelUserRole;
    private javax.swing.JPasswordField jPasswordFieldUserPassword;
    private javax.swing.JTextField jTextFieldUserId;
    private javax.swing.JTextField jTextFieldUserLogin;
    // End of variables declaration//GEN-END:variables
}
