/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.views.users;

import app.controllers.UserController;
import app.entities.User;
import helpers.Dialog;
import helpers.Log;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author raulsm
 */
public class UserShowJInternalFrame extends javax.swing.JInternalFrame {

    private final JDesktopPane jDesktopPanelContainer;
    
    /**
     * Creates new form ConvocatoryShowJInternalFrame
     * @param jDesktopPanelContainer
     */
    public UserShowJInternalFrame(JDesktopPane jDesktopPanelContainer) {
        initComponents();
        this.jDesktopPanelContainer = jDesktopPanelContainer;
        jTextFieldUserId.setVisible(false);
    }

    /**
     * Load Data.
     * @param user
     */
    public void loadData(User user) {
        jTextFieldUserId.setText(String.valueOf(user.getId()));
        
        jTextFieldUserLogin.setText(user.getLogin());
        jPasswordFieldUserPassword.setText(user.getPassword());
        jTextFieldUserRole.setText(user.getRoleName());
        jTextFieldUserMunicipality.setText(user.getMunicipalityName());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUserLogin = new javax.swing.JLabel();
        jTextFieldUserLogin = new javax.swing.JTextField();
        jLabelUserPassword = new javax.swing.JLabel();
        jButtonUserEdit = new javax.swing.JButton();
        jTextFieldUserId = new javax.swing.JTextField();
        jButtonUserDelete = new javax.swing.JButton();
        jPasswordFieldUserPassword = new javax.swing.JPasswordField();
        jLabelUserRole = new javax.swing.JLabel();
        jTextFieldUserRole = new javax.swing.JTextField();
        jLabelUserMunicipality = new javax.swing.JLabel();
        jTextFieldUserMunicipality = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ver Usuario");
        setToolTipText("");

        jLabelUserLogin.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelUserLogin.setText("Login usuario:");

        jTextFieldUserLogin.setEditable(false);
        jTextFieldUserLogin.setToolTipText("Introducir nombre del municipio");
        jTextFieldUserLogin.setEnabled(false);

        jLabelUserPassword.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelUserPassword.setText("Contraseña usuario:");

        jButtonUserEdit.setText("Editar");
        jButtonUserEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserEditActionPerformed(evt);
            }
        });

        jTextFieldUserId.setEditable(false);
        jTextFieldUserId.setEnabled(false);

        jButtonUserDelete.setBackground(new java.awt.Color(255, 153, 153));
        jButtonUserDelete.setText("Eliminar");
        jButtonUserDelete.setBorderPainted(false);
        jButtonUserDelete.setOpaque(true);
        jButtonUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserDeleteActionPerformed(evt);
            }
        });

        jPasswordFieldUserPassword.setEditable(false);
        jPasswordFieldUserPassword.setEnabled(false);

        jLabelUserRole.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelUserRole.setText("Role usuario:");

        jTextFieldUserRole.setEditable(false);
        jTextFieldUserRole.setToolTipText("Introducir nombre del municipio");
        jTextFieldUserRole.setEnabled(false);

        jLabelUserMunicipality.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelUserMunicipality.setText("Municipio usuario:");

        jTextFieldUserMunicipality.setEditable(false);
        jTextFieldUserMunicipality.setToolTipText("Introducir nombre del municipio");
        jTextFieldUserMunicipality.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUserLogin)
                    .addComponent(jLabelUserLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUserPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldUserPassword)
                    .addComponent(jTextFieldUserRole)
                    .addComponent(jLabelUserRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUserMunicipality, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldUserMunicipality)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonUserDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonUserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserMunicipality, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUserMunicipality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonUserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUserDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unused")
    private void jButtonUserEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserEditActionPerformed
        try {

            int id = Integer.parseInt(jTextFieldUserId.getText());
            User user = UserController.findById(id);
            
            UserEditJInternalFrame userEdit = new UserEditJInternalFrame();
        
            jDesktopPanelContainer.add(userEdit);
        
            // Load user info in view
            userEdit.loadData(user);
            
            this.hide();
            
            userEdit.setVisible(true);
        } catch (NumberFormatException e) {
            Log.error(e);
            Dialog.error(e.getMessage(), "Error editar municipio");
        }
    }//GEN-LAST:event_jButtonUserEditActionPerformed

    @SuppressWarnings("unused")
    private void jButtonUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserDeleteActionPerformed
        int input = JOptionPane.showConfirmDialog(null, "Deseas eliminar?");
        // 0=yes, 1=no, 2=cancel
        
        if (input == 0) {
            // Delete
            int id = Integer.parseInt(jTextFieldUserId.getText());
            boolean status = UserController.delete(id);
            
            if (status) {
                Dialog.info("Usuario eliminado correctamente", "Info");
                
                this.hide();
            } else {
                Dialog.error("Usuario no se ha eliminado", "Error");
            }
        }
    }//GEN-LAST:event_jButtonUserDeleteActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUserDelete;
    private javax.swing.JButton jButtonUserEdit;
    private javax.swing.JLabel jLabelUserLogin;
    private javax.swing.JLabel jLabelUserMunicipality;
    private javax.swing.JLabel jLabelUserPassword;
    private javax.swing.JLabel jLabelUserRole;
    private javax.swing.JPasswordField jPasswordFieldUserPassword;
    private javax.swing.JTextField jTextFieldUserId;
    private javax.swing.JTextField jTextFieldUserLogin;
    private javax.swing.JTextField jTextFieldUserMunicipality;
    private javax.swing.JTextField jTextFieldUserRole;
    // End of variables declaration//GEN-END:variables
}
