/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.views.presentation;

import app.Main;
import app.controllers.ConvocatoryController;
import app.controllers.PresentationController;
import app.entities.Convocatory;
import app.entities.Presentation;
import app.entities.User;
import helpers.ComboBox;
import helpers.Dialog;
import helpers.Log;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author raulsm
 */
public class PresentationCreateJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form PresentationJInternalFrame
     */
    public PresentationCreateJInternalFrame() {
        initComponents();
        loadData();
    }

    /**
     * Load Data.
     */
    public void loadData() {
        disableAllInputFiles();
        loadConvocatoriesComboBox();
        loadLoggedUserInfo();
    }

    /**
     * Load Convocatories ComboBox
     */
    private void loadConvocatoriesComboBox() {
        // Traer de base de datos el listado de roles y agregar al combobox
        List<Convocatory> convocatories = ConvocatoryController.list();
        ComboBox.fill(convocatories, jComboBoxConvocatory);
    }

    /**
     * Load Logged User Info
     */
    private void loadLoggedUserInfo() {
        User authUser = Main.getAuthUser();
        jTextFieldUserId.setText(String.valueOf(authUser.getId()));
        jTextFieldUserName.setText(authUser.getLogin());
    }

    /**
     * Disable All Input Files
     */
    private void disableAllInputFiles() {
        jButtonDocumentType1.setEnabled(false);
        jButtonDocumentType2.setEnabled(false);
        jButtonDocumentType3.setEnabled(false);
        jButtonDocumentType4.setEnabled(false);
        jButtonDocumentType5.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConvocatory = new javax.swing.JLabel();
        jButtonMunicipioCreate = new javax.swing.JButton();
        jComboBoxConvocatory = new javax.swing.JComboBox<>();
        jLabelUser = new javax.swing.JLabel();
        jTextFieldUserId = new javax.swing.JTextField();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabelNecesaryDocuments = new javax.swing.JLabel();
        jPanelDocumentType1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonDocumentType1 = new javax.swing.JButton();
        jPanelDocumentType2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonDocumentType2 = new javax.swing.JButton();
        jPanelDocumentType3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonDocumentType3 = new javax.swing.JButton();
        jPanelDocumentType4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButtonDocumentType4 = new javax.swing.JButton();
        jPanelDocumentType5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButtonDocumentType5 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Presentación");
        setToolTipText("");

        jLabelConvocatory.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelConvocatory.setText("Convocatoria:");

        jButtonMunicipioCreate.setText("Crear");
        jButtonMunicipioCreate.setEnabled(false);
        jButtonMunicipioCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMunicipioCreateActionPerformed(evt);
            }
        });

        jComboBoxConvocatory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));

        jLabelUser.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelUser.setText("Nombre del usuario:");

        jTextFieldUserId.setEditable(false);
        jTextFieldUserId.setText("ID");
        jTextFieldUserId.setEnabled(false);

        jTextFieldUserName.setEditable(false);
        jTextFieldUserName.setText("Nombre Usuario");
        jTextFieldUserName.setEnabled(false);

        jLabelNecesaryDocuments.setText("Documentos necesarios:");

        jPanelDocumentType1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Libro Diario");

        jButtonDocumentType1.setText("Agregar");

        javax.swing.GroupLayout jPanelDocumentType1Layout = new javax.swing.GroupLayout(jPanelDocumentType1);
        jPanelDocumentType1.setLayout(jPanelDocumentType1Layout);
        jPanelDocumentType1Layout.setHorizontalGroup(
            jPanelDocumentType1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDocumentType1))
        );
        jPanelDocumentType1Layout.setVerticalGroup(
            jPanelDocumentType1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDocumentType1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonDocumentType1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDocumentType2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Libro Mayor");

        jButtonDocumentType2.setText("Agregar");

        javax.swing.GroupLayout jPanelDocumentType2Layout = new javax.swing.GroupLayout(jPanelDocumentType2);
        jPanelDocumentType2.setLayout(jPanelDocumentType2Layout);
        jPanelDocumentType2Layout.setHorizontalGroup(
            jPanelDocumentType2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDocumentType2))
        );
        jPanelDocumentType2Layout.setVerticalGroup(
            jPanelDocumentType2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDocumentType2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonDocumentType2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDocumentType3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Balance de Sumas y Saldos");
        jLabel3.setToolTipText("");

        jButtonDocumentType3.setText("Agregar");

        javax.swing.GroupLayout jPanelDocumentType3Layout = new javax.swing.GroupLayout(jPanelDocumentType3);
        jPanelDocumentType3.setLayout(jPanelDocumentType3Layout);
        jPanelDocumentType3Layout.setHorizontalGroup(
            jPanelDocumentType3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDocumentType3))
        );
        jPanelDocumentType3Layout.setVerticalGroup(
            jPanelDocumentType3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDocumentType3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonDocumentType3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDocumentType4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Registro de Ingreso de Caja");
        jLabel4.setToolTipText("");

        jButtonDocumentType4.setText("Agregar");

        javax.swing.GroupLayout jPanelDocumentType4Layout = new javax.swing.GroupLayout(jPanelDocumentType4);
        jPanelDocumentType4.setLayout(jPanelDocumentType4Layout);
        jPanelDocumentType4Layout.setHorizontalGroup(
            jPanelDocumentType4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDocumentType4))
        );
        jPanelDocumentType4Layout.setVerticalGroup(
            jPanelDocumentType4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDocumentType4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButtonDocumentType4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDocumentType5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Registro de Movimientos de Bancos");
        jLabel5.setToolTipText("");

        jButtonDocumentType5.setText("Agregar");

        javax.swing.GroupLayout jPanelDocumentType5Layout = new javax.swing.GroupLayout(jPanelDocumentType5);
        jPanelDocumentType5.setLayout(jPanelDocumentType5Layout);
        jPanelDocumentType5Layout.setHorizontalGroup(
            jPanelDocumentType5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDocumentType5))
        );
        jPanelDocumentType5Layout.setVerticalGroup(
            jPanelDocumentType5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDocumentType5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonDocumentType5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDocumentType1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMunicipioCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(544, 544, 544))
                    .addComponent(jLabelConvocatory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addComponent(jLabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUserName))
                    .addComponent(jPanelDocumentType2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDocumentType3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDocumentType4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDocumentType5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNecesaryDocuments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxConvocatory, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelConvocatory, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxConvocatory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNecesaryDocuments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDocumentType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDocumentType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDocumentType3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDocumentType4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDocumentType5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButtonMunicipioCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMunicipioCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMunicipioCreateActionPerformed
        try {
            if (!validateInputs()) {
                throw new Exception("Inputs fieds are invalid.");
            }

//            String name = getInputName();
//            String category = getInputCategory();
            // Presentación create
            // @TODO: Add info!!!
            Presentation presentation = new Presentation();
//            PresentationController.create(presentation);

            Dialog.info("Presentación creado correctamente", "Info");

            cleanInputs();
        } catch (Exception e) {
            Log.error(e);
            Dialog.error(e.getMessage(), "Error creando municipio");
        }
    }//GEN-LAST:event_jButtonMunicipioCreateActionPerformed

    /**
     * Clean Inputs
     */
    private void cleanInputs() {
        // @TODO: Clean Inputs
    }

    /**
     * Validate Inputs.
     *
     * @return True if inputs are valid
     */
    private Boolean validateInputs() {
        // @TODO: Validation!
        return false;
//        return validateInputName() && validateInputCategory();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDocumentType1;
    private javax.swing.JButton jButtonDocumentType2;
    private javax.swing.JButton jButtonDocumentType3;
    private javax.swing.JButton jButtonDocumentType4;
    private javax.swing.JButton jButtonDocumentType5;
    private javax.swing.JButton jButtonMunicipioCreate;
    private javax.swing.JComboBox<String> jComboBoxConvocatory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelConvocatory;
    private javax.swing.JLabel jLabelNecesaryDocuments;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanelDocumentType1;
    private javax.swing.JPanel jPanelDocumentType2;
    private javax.swing.JPanel jPanelDocumentType3;
    private javax.swing.JPanel jPanelDocumentType4;
    private javax.swing.JPanel jPanelDocumentType5;
    private javax.swing.JTextField jTextFieldUserId;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
