/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package app.views.presentation;

import app.controllers.PresentationController;
import app.entities.Presentation;
import helpers.Dialog;
import helpers.Log;
import java.awt.Color;
import javax.swing.JDesktopPane;

/**
 *
 * @author raulsm
 */
public class PresentationCreateJInternalFrame extends javax.swing.JInternalFrame {

    private final JDesktopPane jDesktopPanelContainer;
    
    /**
     * Creates new form PresentationJInternalFrame
     */
    public PresentationCreateJInternalFrame(JDesktopPane jDesktopPanelContainer) {
        initComponents();
        this.jDesktopPanelContainer = jDesktopPanelContainer;
        loadData();
    }

    /**
     * Load Data.
     */
    public void loadData() {        
        // @TODO:
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConvocatory = new javax.swing.JLabel();
        jButtonMunicipioCreate = new javax.swing.JButton();
        jComboBoxConvocatory = new javax.swing.JComboBox<>();
        jLabelUser = new javax.swing.JLabel();
        jTextFieldUserId = new javax.swing.JTextField();
        jTextFieldUserName = new javax.swing.JTextField();
        jCheckBoxDocumentTypeId5 = new javax.swing.JCheckBox();
        jCheckBoxDocumentTypeId4 = new javax.swing.JCheckBox();
        jCheckBoxDocumentTypeId3 = new javax.swing.JCheckBox();
        jCheckBoxDocumentTypeId2 = new javax.swing.JCheckBox();
        jCheckBoxDocumentTypeId1 = new javax.swing.JCheckBox();
        jLabelNecesaryDocuments = new javax.swing.JLabel();
        jPanelDocumentType1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonDocumentType1 = new javax.swing.JButton();
        jPanelDocumentType2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonDocumentType2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Presentación");
        setToolTipText("");

        jLabelConvocatory.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelConvocatory.setText("Convocatoria:");

        jButtonMunicipioCreate.setText("Crear");
        jButtonMunicipioCreate.setEnabled(false);
        jButtonMunicipioCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMunicipioCreateActionPerformed(evt);
            }
        });

        jComboBoxConvocatory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        jComboBoxConvocatory.setEnabled(false);

        jLabelUser.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabelUser.setText("Nombre del municipio:");

        jTextFieldUserId.setEditable(false);
        jTextFieldUserId.setText("ID");
        jTextFieldUserId.setEnabled(false);

        jTextFieldUserName.setEditable(false);
        jTextFieldUserName.setText("Nombre Usuario");
        jTextFieldUserName.setEnabled(false);

        jCheckBoxDocumentTypeId5.setText("Registro de Movimientos de Bancos");

        jCheckBoxDocumentTypeId4.setText("Registro de Ingreso de Caja");

        jCheckBoxDocumentTypeId3.setText("Balance de Sumas y Saldos");

        jCheckBoxDocumentTypeId2.setText("Libro Mayor");

        jCheckBoxDocumentTypeId1.setText("Libro Diario");

        jLabelNecesaryDocuments.setText("Documentos necesarios:");

        jPanelDocumentType1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Libro Diario");

        jButtonDocumentType1.setText("Agregar");

        javax.swing.GroupLayout jPanelDocumentType1Layout = new javax.swing.GroupLayout(jPanelDocumentType1);
        jPanelDocumentType1.setLayout(jPanelDocumentType1Layout);
        jPanelDocumentType1Layout.setHorizontalGroup(
            jPanelDocumentType1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDocumentType1))
        );
        jPanelDocumentType1Layout.setVerticalGroup(
            jPanelDocumentType1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDocumentType1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonDocumentType1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDocumentType2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Libro Mayor");

        jButtonDocumentType2.setText("Agregar");

        javax.swing.GroupLayout jPanelDocumentType2Layout = new javax.swing.GroupLayout(jPanelDocumentType2);
        jPanelDocumentType2.setLayout(jPanelDocumentType2Layout);
        jPanelDocumentType2Layout.setHorizontalGroup(
            jPanelDocumentType2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDocumentType2))
        );
        jPanelDocumentType2Layout.setVerticalGroup(
            jPanelDocumentType2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocumentType2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDocumentType2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonDocumentType2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNecesaryDocuments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCheckBoxDocumentTypeId1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCheckBoxDocumentTypeId2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCheckBoxDocumentTypeId3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCheckBoxDocumentTypeId4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCheckBoxDocumentTypeId5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDocumentType1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMunicipioCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(544, 544, 544))
                    .addComponent(jLabelConvocatory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addComponent(jComboBoxConvocatory, 0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUserName))
                    .addComponent(jPanelDocumentType2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelConvocatory, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxConvocatory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNecesaryDocuments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDocumentTypeId1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDocumentTypeId2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDocumentTypeId3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDocumentTypeId4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDocumentTypeId5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDocumentType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDocumentType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(jButtonMunicipioCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMunicipioCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMunicipioCreateActionPerformed
        try {
            if (!validateInputs()) {
                throw new Exception("Inputs fieds are invalid.");
            }

//            String name = getInputName();
//            String category = getInputCategory();

            // Presentación create
//            Presentation presentation = new Presentation();
//            PresentationController.create(presentation);
            
            Dialog.info("Presentación creado correctamente", "Info");
            
            cleanInputs();
        } catch (Exception e) {
            Log.error(e);
            Dialog.error(e.getMessage(), "Error creando municipio");
        }
    }//GEN-LAST:event_jButtonMunicipioCreateActionPerformed

    /**
     * Clean Inputs
     */
    private void cleanInputs() {
        jTextFieldPresentaciónName.setText("");
        jComboBoxPresentaciónCategory.setSelectedIndex(0);
        jButtonPresentaciónCreate.setEnabled(validateInputs());
    }
    
    /**
     * Validate Inputs.
     *
     * @return True if inputs are valid
     */
    private Boolean validateInputs() {
        return validateInputName() && validateInputCategory();
    }

    /**
     * Validate Input Name.
     *
     * @return
     */
    private Boolean validateInputName() {
        String name = getInputName();
        Boolean isValid = name.length() > 0 && name.length() <= 30;

        if (isValid || name.length() == 0) {
            jTextFieldPresentaciónName.setBackground(Color.white);
        } else {
            jTextFieldPresentaciónName.setBackground(Color.orange);
        }

        return isValid;
    }

    /**
     * Validate Input Category.
     *
     * @return
     */
    private Boolean validateInputCategory() {
        // TODO: Validation
        // String category = getInputCategory();
        Boolean isValid = true;

        if (isValid) {
            jComboBoxPresentaciónCategory.setBackground(Color.white);
        } else {
            jComboBoxPresentaciónCategory.setBackground(Color.orange);
        }

        return isValid;
    }

    /**
     * Get Input Name.
     *
     * @return Input Name
     */
    private String getInputName() {
        return jTextFieldPresentaciónName.getText();
    }

    /**
     * Get Input Category.
     *
     * @return Input Category.
     */
    private String getInputCategory() {
        return jComboBoxPresentaciónCategory.getSelectedItem().toString();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDocumentType1;
    private javax.swing.JButton jButtonDocumentType2;
    private javax.swing.JButton jButtonMunicipioCreate;
    private javax.swing.JCheckBox jCheckBoxDocumentTypeId1;
    private javax.swing.JCheckBox jCheckBoxDocumentTypeId2;
    private javax.swing.JCheckBox jCheckBoxDocumentTypeId3;
    private javax.swing.JCheckBox jCheckBoxDocumentTypeId4;
    private javax.swing.JCheckBox jCheckBoxDocumentTypeId5;
    private javax.swing.JComboBox<String> jComboBoxConvocatory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelConvocatory;
    private javax.swing.JLabel jLabelNecesaryDocuments;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanelDocumentType1;
    private javax.swing.JPanel jPanelDocumentType2;
    private javax.swing.JTextField jTextFieldUserId;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
